version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ivs-proxy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ulswqinw5wd5"
s3_prefix = "ivs-proxy"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SubnetIds=\"subnet-0f13b3de9426a8d92,subnet-05bfd90c678f1af2a\" SecurityGroupIds=\"sg-0e1fe77a8bc004a11\""
